stages:
  - build
  - deploy

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/

.default-cache: &default-cache
  before_script:
    - npm ci --cache .npm --prefer-offline

build:
  extends:
    - .default-cache
  image: node:16.13.1-alpine
  stage: build
  script:
    - npm install
    - npm run build
  artifacts: 
    paths:
      - build/

deploy:
  image: ubuntu:latest
  stage: deploy
  script:
    - apt -qq update && apt upgrade -qqy openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY}" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "${SSH_KNOWN_HOSTS}" >> ~/.ssh/known_hosts
    - rsync -a --progress
      --human-readable --delete
      --exclude-from '.gitignore'
      --exclude .gitignore
      --exclude .git
      ./build/* deploy@$REMOTE_HOST:~/realworld/public
